on: 
  pull_request:
    paths:
      - 'configs/*.json'

name: Check Config

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - name: check if configs/*.json is sorted alphabetically
        run: |
          for config in configs/*.json; do
            .github/workflows/check-config.sh $config
          done
