on: [ push, pull_request ]

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - name: install jsonlint
        run: npm install jsonlint
      - name: check if config.json is valid JSON and sorted alphabetically
        run: .github/workflows/check-config.sh config.json
