on: 
  pull_request:
    paths:
      - 'configs/go.json'

name: Check Config

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - name: check if configs/go.json is sorted alphabetically
        run: .github/workflows/check-config.sh configs/go.json
