# Trigger the execution of copy-workflow.yml, in batches of 8 repositories.
# This workflow is needed since GitHub Actions limits the matrix size to 256 jobs.
# We use one job per repository per file.

on:
  push:
    branches: [ master, testing ]

env:
  # Number of repositories in a batch.
  # Deployment jobs in the same batch are run sequentially.
  # With ~180 repos, this means we'll run around 9 instances of the copy workflow in parallel.
  # This is (hopefully) sufficient to prevent us from triggering GitHub Action's abuse detection mechanism.
  MAX_REPOS_PER_WORKFLOW: 20

jobs:
  matrix:
    name: Trigger copy workflows
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TARGETS=()
          for config in configs/*.json; do
            if [[ $GITHUB_REF == refs/heads/testing && $config != configs/testing.json ]]; then
              continue
            fi
            if [[ $GITHUB_REF != refs/heads/testing && $config == configs/testing.json ]]; then
              continue
            fi
            TARGETS+=$(jq "[.repositories[] | $(jq '.defaults' $CONFIG) + .] | _nwise(${{ env.MAX_REPOS_PER_WORKFLOW }})" $CONFIG | jq -sc '. | to_entries')
          done
          echo "::set-output name=targets::$TARGETS"
  dispatch:
    needs: [ matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We end up with multiple "dispatch" jobs,
        # one per TARGETS "key" chunk above with a "value" array.
        # For each "dispatch" job, matrix.cfg.value is an array, like:
        #
        #   [
        #     {"target": "repo1", "files": [".github/workflows/go-check.yml"]}, 
        #     {"target": "repo2", "files": [".github/workflows/go-check.yml", ".github/workflows/go-test.yml"]}
        #   ]
        #
        # All array item in a batch are sourced from the same json config file.
        # The triggered copy-workflow jobs use that final array as their matrix.
        # As such, we'll end up with one copy-workflow parallel job per target.
        cfg: ${{ fromJson(needs.matrix.outputs.targets) }}
    name: Start copy workflow (batch ${{ matrix.cfg.key }})
    steps:
      - uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # v1.1.0
        with:
          workflow: "Deploy" # "name" attribute of copy-workflow.yml
          token: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
          inputs: '{ "head_commit_url": ${{ toJson(github.event.head_commit.url) }}, "targets": ${{ toJson(toJson(matrix.cfg.value)) }} }'
